/**
 * @description Database types
 *
 * Whenever possible it would be better to just use the types provided by prisma directly.
 * However, there are some cases where we need to create our own copies types.
 *
 * Specifically, we need to create our own types for the following reasons:
 * 1. The types generated by prisma are not serializable. Some of them contain Date objects which are not serializable.
 */

export type Strain = {
  id: number;
  name: string;
  batchDate: string;
  THC: number;
  productType: string;
  producerId: number;
  producerName: string;
  image: string;

  // optional relation fields
  reviews?: Review[];
  tags?: Tags[];
  producer?: Producer;
};

export type Tags = {
  id: number;
  weight: number;
  color: string;
  lean: number;
  name: string;
};

export type Review = {
  id: number;
  rating: number;
  comment: string;
  profileId: string;

  // optional relation fields
  createdAt?: string;
  profileName?: string;
  strainId?: number;
  strainName?: string;
};

export type Producer = {
  id: number;
  name: string;
  location: string;
  website: string;
  bannerImage: string;
  strains: Strain[];
};
