/**
 * @description Database types
 *
 * Whenever possible it would be better to just use the types provided by prisma directly.
 * However, there are some cases where we need to create our own copies types.
 *
 * Specifically, we need to create our own types for the following reasons:
 * 1. The types generated by prisma are not serializable. Some of them contain Date objects which are not serializable.
 */

export type Strain = {
  id: number;
  name: string;
  batchDate: string;
  THC: number;
  productType: string;
  image: string;

  producerId: number;
  producerName: string;
  Producer?: Producer;

  // optional relation fields
  Reviews?: Review[];
  TerpTags?: TerpTag[];
};

export type TerpTag = {
  id: number;
  color: string;
  lean: number;
  name: string;
};

export type Profile = {
  id: number;
  name: string;
  image: string;
  Reviews?: Review[];
};

export type Review = {
  id: number;
  rating: number;
  comment: string;

  // optional relation fields
  TerpTag?: TerpTag;
  TerpTagId?: number;

  createdAt?: string;
  profileName?: string;
  Profile?: Profile;

  strainId?: number;
  strainName?: string;
};

export type Producer = {
  id: number;
  name: string;
  location: string;
  website: string;
  bannerImage: string;

  Strains?: Strain[];
};
